package com.cuius.home.entity;
// Generated Jul 3, 2019 5:21:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PropertyImage generated by hbm2java
 */
@Entity
@Table(name="property_image"
    ,catalog="cuius_home"
)
public class PropertyImage  implements java.io.Serializable {


     private Integer imageId;
     private String imageUrl;
     private Set properties = new HashSet(0);

    public PropertyImage() {
    }

	
    public PropertyImage(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public PropertyImage(String imageUrl, Set properties) {
       this.imageUrl = imageUrl;
       this.properties = properties;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="image_id", unique=true, nullable=false)
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    
    @Column(name="image_url", nullable=false, length=500)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="propertyImage")
    public Set getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set properties) {
        this.properties = properties;
    }




}


