package com.cuius.home.entity;
// Generated Jul 3, 2019 5:21:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PropertyImage generated by hbm2java
 */
@Entity
@Table(name = "property_image"
        , catalog = "cuius_home"
)
public class PropertyImage implements java.io.Serializable {

    private Property property;
    private Integer imageId;
    private String imageUrl;
    private Set properties = new HashSet(0);

    public PropertyImage() {
    }


    public PropertyImage(Property property, String imageUrl) {
        this.property = property;
        this.imageUrl = imageUrl;
    }

    public PropertyImage(Property property, String imageUrl, Set properties) {
        this.property = property;
        this.imageUrl = imageUrl;
        this.properties = properties;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "image_id", unique = true, nullable = false)
    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "property_id", nullable = false)
    public Property getProperty() {
        return property;
    }

    public void setProperty(Property property) {
        this.property = property;
    }

    @Column(name = "image_url", nullable = false, length = 500)
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "propertyImage")
    public Set getProperties() {
        return this.properties;
    }

    public void setProperties(Set properties) {
        this.properties = properties;
    }


}


