package com.cuius.home.entity;
// Generated Jul 3, 2019 5:21:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PropertyHistory generated by hbm2java
 */
@Entity
@Table(name="property_history"
    ,catalog="cuius_home"
)
public class PropertyHistory  implements java.io.Serializable {


     private Long historyId;
     private Property property;
     private PropertyManager propertyManager;
     private String detail;
     private double price;
     private String source;

    public PropertyHistory() {
    }

    public PropertyHistory(Property property, PropertyManager propertyManager, String detail, double price, String source) {
       this.property = property;
       this.propertyManager = propertyManager;
       this.detail = detail;
       this.price = price;
       this.source = source;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="history_id", unique=true, nullable=false)
    public Long getHistoryId() {
        return this.historyId;
    }
    
    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="property_id", nullable=false)
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agent_id", nullable=false)
    public PropertyManager getPropertyManager() {
        return this.propertyManager;
    }
    
    public void setPropertyManager(PropertyManager propertyManager) {
        this.propertyManager = propertyManager;
    }

    
    @Column(name="detail", nullable=false, length=500)
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="source", nullable=false, length=200)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }




}


