package com.cuius.home.entity;
// Generated Jul 3, 2019 5:21:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PropertyManager generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name="property_manager"
    ,catalog="cuius_home"
)
public class PropertyManager  implements java.io.Serializable {


     private Integer agentId;
     private String fullName;
     private String address;
     private Date dateJoined;
     private String shortBio;
     private String companyName;
     private String officeNumber;
     private String mobileNumber;
     private String faxNumber;
     private String emailAddress;
     private String facebookLink;
     private String twitterLink;
     private String instagramLink;
     private String password;
     private Set propertyHistories = new HashSet(0);
     private Set properties = new HashSet(0);

    public PropertyManager() {
    }

	
    public PropertyManager(String fullName, String address, Date dateJoined, String shortBio, String companyName, String officeNumber, String mobileNumber, String emailAddress, String password) {
        this.fullName = fullName;
        this.address = address;
        this.dateJoined = dateJoined;
        this.shortBio = shortBio;
        this.companyName = companyName;
        this.officeNumber = officeNumber;
        this.mobileNumber = mobileNumber;
        this.emailAddress = emailAddress;
        this.password = password;
    }
    public PropertyManager(String fullName, String address, Date dateJoined, String shortBio, String companyName, String officeNumber, String mobileNumber, String faxNumber, String emailAddress, String facebookLink, String twitterLink, String instagramLink, String password, Set propertyHistories, Set properties) {
       this.fullName = fullName;
       this.address = address;
       this.dateJoined = dateJoined;
       this.shortBio = shortBio;
       this.companyName = companyName;
       this.officeNumber = officeNumber;
       this.mobileNumber = mobileNumber;
       this.faxNumber = faxNumber;
       this.emailAddress = emailAddress;
       this.facebookLink = facebookLink;
       this.twitterLink = twitterLink;
       this.instagramLink = instagramLink;
       this.password = password;
       this.propertyHistories = propertyHistories;
       this.properties = properties;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="agent_id", unique=true, nullable=false)
    public Integer getAgentId() {
        return this.agentId;
    }
    
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    
    @Column(name="full_name", nullable=false, length=500)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="address", nullable=false, length=500)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_joined", nullable=false, length=26)
    public Date getDateJoined() {
        return this.dateJoined;
    }
    
    public void setDateJoined(Date dateJoined) {
        this.dateJoined = dateJoined;
    }

    
    @Column(name="short_bio", nullable=false, length=5000)
    public String getShortBio() {
        return this.shortBio;
    }
    
    public void setShortBio(String shortBio) {
        this.shortBio = shortBio;
    }

    
    @Column(name="company_name", nullable=false, length=100)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="office_number", nullable=false, length=20)
    public String getOfficeNumber() {
        return this.officeNumber;
    }
    
    public void setOfficeNumber(String officeNumber) {
        this.officeNumber = officeNumber;
    }

    
    @Column(name="mobile_number", nullable=false, length=20)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="fax_number", length=20)
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    
    @Column(name="email_address", nullable=false, length=100)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="facebook_link", length=500)
    public String getFacebookLink() {
        return this.facebookLink;
    }
    
    public void setFacebookLink(String facebookLink) {
        this.facebookLink = facebookLink;
    }

    
    @Column(name="twitter_link", length=500)
    public String getTwitterLink() {
        return this.twitterLink;
    }
    
    public void setTwitterLink(String twitterLink) {
        this.twitterLink = twitterLink;
    }

    
    @Column(name="instagram_link", length=500)
    public String getInstagramLink() {
        return this.instagramLink;
    }
    
    public void setInstagramLink(String instagramLink) {
        this.instagramLink = instagramLink;
    }

    @Column(name="password", nullable=false, length=1500)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="propertyManager")
    public Set getPropertyHistories() {
        return this.propertyHistories;
    }
    
    public void setPropertyHistories(Set propertyHistories) {
        this.propertyHistories = propertyHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="propertyManager")
    public Set getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set properties) {
        this.properties = properties;
    }




}


