package com.cuius.home.entity;
// Generated Jul 3, 2019 5:21:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name="property"
    ,catalog="cuius_home"
)
public class Property  implements java.io.Serializable {


     private Integer propertyId;
     private PropertyCategory propertyCategory;
     private PropertyImage propertyImage;
     private PropertyManager propertyManager;
     private String propertyName;
     private String detailedDescription;
     private String address;
     private String town;
     private String region;
     private Date yearBuilt;
     private Integer totalRooms;
     private Integer totalBeds;
     private Integer totalBaths;
     private double totalLandAreaSqmts;
     private double totalBuildingAreaSqmts;
     private String status;
     private String latitude;
     private String longitude;
     private String priceRent;
     private String priceSale;
     private Set propertyHistories = new HashSet(0);

    public Property() {
    }

	
    public Property(PropertyCategory propertyCategory, PropertyImage propertyImage, PropertyManager propertyManager, String propertyName, String detailedDescription, String address, String town, String region, double totalLandAreaSqmts, double totalBuildingAreaSqmts, String status, String priceRent, String priceSale) {
        this.propertyCategory = propertyCategory;
        this.propertyImage = propertyImage;
        this.propertyManager = propertyManager;
        this.propertyName = propertyName;
        this.detailedDescription = detailedDescription;
        this.address = address;
        this.town = town;
        this.region = region;
        this.totalLandAreaSqmts = totalLandAreaSqmts;
        this.totalBuildingAreaSqmts = totalBuildingAreaSqmts;
        this.status = status;
        this.priceRent = priceRent;
        this.priceSale = priceSale;
    }
    public Property(PropertyCategory propertyCategory, PropertyImage propertyImage, PropertyManager propertyManager, String propertyName, String detailedDescription, String address, String town, String region, Date yearBuilt, Integer totalRooms, Integer totalBeds, Integer totalBaths, double totalLandAreaSqmts, double totalBuildingAreaSqmts, String status, String latitude, String longitude, String priceRent, String priceSale, Set propertyHistories) {
       this.propertyCategory = propertyCategory;
       this.propertyImage = propertyImage;
       this.propertyManager = propertyManager;
       this.propertyName = propertyName;
       this.detailedDescription = detailedDescription;
       this.address = address;
       this.town = town;
       this.region = region;
       this.yearBuilt = yearBuilt;
       this.totalRooms = totalRooms;
       this.totalBeds = totalBeds;
       this.totalBaths = totalBaths;
       this.totalLandAreaSqmts = totalLandAreaSqmts;
       this.totalBuildingAreaSqmts = totalBuildingAreaSqmts;
       this.status = status;
       this.latitude = latitude;
       this.longitude = longitude;
       this.priceRent = priceRent;
       this.priceSale = priceSale;
       this.propertyHistories = propertyHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="property_id", unique=true, nullable=false)
    public Integer getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public PropertyCategory getPropertyCategory() {
        return this.propertyCategory;
    }
    
    public void setPropertyCategory(PropertyCategory propertyCategory) {
        this.propertyCategory = propertyCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="image_id", nullable=false)
    public PropertyImage getPropertyImage() {
        return this.propertyImage;
    }
    
    public void setPropertyImage(PropertyImage propertyImage) {
        this.propertyImage = propertyImage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agent_id", nullable=false)
    public PropertyManager getPropertyManager() {
        return this.propertyManager;
    }
    
    public void setPropertyManager(PropertyManager propertyManager) {
        this.propertyManager = propertyManager;
    }

    
    @Column(name="property_name", nullable=false, length=500)
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    
    @Column(name="detailed_description", nullable=false, length=5000)
    public String getDetailedDescription() {
        return this.detailedDescription;
    }
    
    public void setDetailedDescription(String detailedDescription) {
        this.detailedDescription = detailedDescription;
    }

    
    @Column(name="address", nullable=false, length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="town", nullable=false, length=50)
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }

    
    @Column(name="region", nullable=false, length=50)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="year_built", length=4)
    public Date getYearBuilt() {
        return this.yearBuilt;
    }
    
    public void setYearBuilt(Date yearBuilt) {
        this.yearBuilt = yearBuilt;
    }

    
    @Column(name="total_rooms")
    public Integer getTotalRooms() {
        return this.totalRooms;
    }
    
    public void setTotalRooms(Integer totalRooms) {
        this.totalRooms = totalRooms;
    }

    
    @Column(name="total_beds")
    public Integer getTotalBeds() {
        return this.totalBeds;
    }
    
    public void setTotalBeds(Integer totalBeds) {
        this.totalBeds = totalBeds;
    }

    
    @Column(name="total_baths")
    public Integer getTotalBaths() {
        return this.totalBaths;
    }
    
    public void setTotalBaths(Integer totalBaths) {
        this.totalBaths = totalBaths;
    }

    
    @Column(name="total_land_area_sqmts", nullable=false, precision=22, scale=0)
    public double getTotalLandAreaSqmts() {
        return this.totalLandAreaSqmts;
    }
    
    public void setTotalLandAreaSqmts(double totalLandAreaSqmts) {
        this.totalLandAreaSqmts = totalLandAreaSqmts;
    }

    
    @Column(name="total_building_area_sqmts", nullable=false, precision=22, scale=0)
    public double getTotalBuildingAreaSqmts() {
        return this.totalBuildingAreaSqmts;
    }
    
    public void setTotalBuildingAreaSqmts(double totalBuildingAreaSqmts) {
        this.totalBuildingAreaSqmts = totalBuildingAreaSqmts;
    }

    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="latitude", length=20)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", length=20)
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="price_rent", nullable=false, length=50)
    public String getPriceRent() {
        return this.priceRent;
    }
    
    public void setPriceRent(String priceRent) {
        this.priceRent = priceRent;
    }

    
    @Column(name="price_sale", nullable=false, length=50)
    public String getPriceSale() {
        return this.priceSale;
    }
    
    public void setPriceSale(String priceSale) {
        this.priceSale = priceSale;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="property")
    public Set getPropertyHistories() {
        return this.propertyHistories;
    }
    
    public void setPropertyHistories(Set propertyHistories) {
        this.propertyHistories = propertyHistories;
    }




}


